In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
demo=pd.read_csv(r'C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\combined_aadhar_demographic.csv')

In [3]:
demo

,date,state,district,pincode,demo_age_5_17,demo_age_17_
0,01-03-2025,Uttar Pradesh,Gorakhpur,273213,49,529
1,01-03-2025,Andhra Pradesh,Chittoor,517132,22,375
2,01-03-2025,Gujarat,Rajkot,360006,65,765
3,01-03-2025,Andhra Pradesh,Srikakulam,532484,24,314
4,01-03-2025,Rajasthan,Udaipur,313801,45,785
...,...,...,...,...,...,...
2071695,31-10-2025,Uttar Pradesh,Etah,207250,2,17
2071696,31-10-2025,Uttar Pradesh,Etah,207401,1,27
2071697,31-10-2025,Uttar Pradesh,Etawah,206003,3,10
2071698,31-10-2025,Uttar Pradesh,Etawah,206125,1,25
2071699,31-10-2025,Uttar Pradesh,Etawah,206126,1,25

**Demographic:**
This data shows how many people updated their Aadhaar demographic details, grouped by date, state, district, and pincode, split by age groups.

**Date:** it is the activity date

**state:** the state where the Aadhaar updates happened

**distict:** the district with in the state

**pincode:** the postal area where the update activity accurred

**demo_age_5_17:** umber of demographic updates done for people aged 5-17 years

**demo_age_17_:**number of demographic updates done for people aged 17 years and above

In [4]:
enrol=pd.read_csv(r"C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\combined_aadhar_enrolment.csv")

In [5]:
enrol

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,Telangana,Hyderabad,500045,4,5,1
1006025,31-12-2025,Telangana,Hyderabad,500057,0,2,0
1006026,31-12-2025,Telangana,Hyderabad,500061,4,2,0
1006027,31-12-2025,Telangana,Hyderabad,500062,1,4,0
1006028,31-12-2025,Telangana,Hyderabad,500095,0,1,0

**date:** the date on which new Aadhaar enrolment were recorded

**state:** the state where the enrolment took place

**district:** the district with in the state

**pincode:** the postal area where enrolemtn activity happened

**age_0_5:** the nuumber of children aged 0_5 years newly enrolled for Aadhaar

**age_5_17:** number of childern aged 5-17 years newly enrolled

**age_18_greater:** number of adults (18+) enrolling for Aadhaar for the first time

In [6]:
bio=pd.read_csv(r"C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\combined_aadhar_biometric.csv")

In [7]:
bio

,date,state,district,pincode,bio_age_5_17,bio_age_17_
0,01-03-2025,Haryana,Mahendragarh,123029,280,577
1,01-03-2025,Bihar,Madhepura,852121,144,369
2,01-03-2025,Jammu and Kashmir,Punch,185101,643,1091
3,01-03-2025,Bihar,Bhojpur,802158,256,980
4,01-03-2025,Tamil Nadu,Madurai,625514,271,815
...,...,...,...,...,...,...
1861103,07-11-2025,Kerala,Ernakulam,682020,1,6
1861104,07-11-2025,Kerala,Ernakulam,682022,1,0
1861105,07-11-2025,Kerala,Ernakulam,682023,0,1
1861106,07-11-2025,Kerala,Ernakulam,682025,3,6
1861107,07-11-2025,Kerala,Ernakulam,682026,1,3

**date:** the date on which biometric updates were recorded

**state:** the state where the biometric update took place

**distric:** the district with in the state

**pincode:** the postal area where the biometric update activity occurred

**bio_age_5_17:** the number of biometri updates done for people aged 5 -17 years 

**bio_age_17:** numberof biometric updates done for people aged 17 years and above

In [8]:
for df in [enrol, demo, bio]:
    df['state'] = df['state'].str.strip().str.title()
    df['district'] = df['district'].str.strip().str.title()
    df['date'] = pd.to_datetime(df['date'], dayfirst=True)

converting state,district,date into valid values no extra space and same formate like title

In [9]:
merged_1 = enrol.merge(
    demo,
    on=['date', 'state', 'district', 'pincode'],
    how='outer'
)

we starting merge of enrollment and demographic data = merged_1

In [10]:
aadhar_df = merged_1.merge(
    bio,
    on=['date', 'state', 'district', 'pincode'],
    how='outer'
)

now merged_1 is added of biometric so all 3 datasets are merged

In [11]:
aadhar_df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_
0,2025-03-01,Andaman & Nicobar Islands,Andamans,744101,NaN,NaN,NaN,NaN,NaN,16.0,193.0
1,2025-03-01,Andaman And Nicobar Islands,Nicobar,744301,NaN,NaN,NaN,16.0,180.0,101.0,48.0
2,2025-03-01,Andaman And Nicobar Islands,Nicobar,744301,NaN,NaN,NaN,16.0,180.0,101.0,48.0
3,2025-03-01,Andaman And Nicobar Islands,Nicobar,744302,NaN,NaN,NaN,NaN,NaN,15.0,12.0
4,2025-03-01,Andaman And Nicobar Islands,Nicobar,744303,NaN,NaN,NaN,NaN,NaN,46.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...
2952416,2025-12-31,West Bengal,West Midnapore,721426,0.0,1.0,0.0,NaN,NaN,NaN,NaN
2952417,2025-12-31,West Bengal,West Midnapore,721504,1.0,0.0,0.0,NaN,NaN,NaN,NaN
2952418,2025-12-31,West Bengal,West Midnapore,721506,1.0,1.0,0.0,NaN,NaN,NaN,NaN
2952419,2025-12-31,West Bengal,West Midnapore,721507,1.0,0.0,0.0,NaN,NaN,NaN,NaN
2952420,2025-12-31,West Bengal,West Midnapore,721517,2.0,1.0,0.0,NaN,NaN,NaN,NaN

In [12]:
aadhar_df.shape

(2952421, 11)

In [13]:
aadhar_df.isna().sum()

date                    0
state                   0
district                0
pincode                 0
age_0_5           1696652
age_5_17          1696652
age_18_greater    1696652
demo_age_5_17      768897
demo_age_17_       768897
bio_age_5_17       693611
bio_age_17_        693611
dtype: int64

we need to clean the null values

In [14]:
aadhar_df.duplicated(
    subset=['date','state','district','pincode']
).sum()

np.int64(625161)

and we found some duplicate values to

In [15]:
keys = ['date', 'state', 'district', 'pincode']

enrol_dups = enrol.duplicated(subset=keys, keep=False).sum()
demo_dups  = demo.duplicated(subset=keys, keep=False).sum()
bio_dups   = bio.duplicated(subset=keys, keep=False).sum()

enrol_dups, demo_dups, bio_dups

(np.int64(47437), np.int64(949382), np.int64(193491))

we are spliting the data into 3 parts like enrol_duplicates , demographic duplicated and biometric duplicated

In [16]:
enrol_clean = (
    enrol
    .groupby(keys, as_index=False)
    .agg({
        'age_0_5': 'sum',
        'age_5_17': 'sum',
        'age_18_greater': 'sum'
    })
)

This code groups the enrollment data by key fields like date and location, and then sums the enrollment counts for different age groups (0–5, 5–17, and 18+).
The result is a cleaned dataset with total enrollments per age group for each group.

In [17]:
demo_clean = (
    demo
    .groupby(keys, as_index=False)
    .agg({
        'demo_age_5_17': 'sum',
        'demo_age_17_': 'sum'
    })
)

This code groups the demographic data by key fields like date and location, and then sums the demographic counts for different age groups (0–5, 5–17, and 18+).
The result is a cleaned dataset with total enrollments per age group for each group.

In [18]:
bio_clean = (
    bio
    .groupby(keys, as_index=False)
    .agg({
        'bio_age_5_17': 'sum',
        'bio_age_17_': 'sum'
    })
)

This code groups the biometric data by key fields like date and location, and then sums the biometric counts for different age groups (0–5, 5–17, and 18+).
The result is a cleaned dataset with total enrollments per age group for each group.

In [19]:
enrol_clean.duplicated(subset=keys).sum()

np.int64(0)

In [20]:
demo_clean.duplicated(subset=keys).sum()

np.int64(0)

In [21]:
bio_clean.duplicated(subset=keys).sum()

np.int64(0)

In [22]:
aadhar_df = (
    enrol_clean
    .merge(demo_clean, on=keys, how='outer')
    .merge(bio_clean, on=keys, how='outer')
)

In [23]:
aadhar_df.duplicated(subset=keys).sum()

np.int64(0)

there is no duplicates now

In [ ]:
aadhar_df.isna().sum()

In [24]:
activity_cols = [
    'age_0_5','age_5_17','age_18_greater',
    'demo_age_5_17','demo_age_17_',
    'bio_age_5_17','bio_age_17_'
]

aadhar_df[activity_cols] = aadhar_df[activity_cols].fillna(0).astype(int)

we have observed some null values in that place we fill 0

In [25]:
aadhar_df.duplicated(subset=keys).sum()

np.int64(0)

In [26]:
(aadhar_df[activity_cols] < 0).sum()

age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
dtype: int64

cheaking the activity columns is there any negative nothing is negative

In [27]:
aadhar_df['total_activity'] = aadhar_df[activity_cols].sum(axis=1)
aadhar_df['total_activity'].describe()

count    2.327260e+06
mean     5.349380e+01
std      2.795450e+02
min      0.000000e+00
25%      4.000000e+00
50%      1.200000e+01
75%      3.600000e+01
max      4.586100e+04
Name: total_activity, dtype: float64

main we are adding all the enrolment ,demographic and biometric totals into one = total_activity

In [28]:
aadhar_df.to_csv(r"C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\final_aadhar_data.csv", index=False)

In [29]:
aadhar_df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity
0,2025-03-01,Andaman & Nicobar Islands,Andamans,744101,0,0,0,0,0,16,193,209
1,2025-03-01,Andaman And Nicobar Islands,Nicobar,744301,0,0,0,32,360,101,48,541
2,2025-03-01,Andaman And Nicobar Islands,Nicobar,744302,0,0,0,0,0,15,12,27
3,2025-03-01,Andaman And Nicobar Islands,Nicobar,744303,0,0,0,0,0,46,27,73
4,2025-03-01,Andaman And Nicobar Islands,Nicobar,744304,0,0,0,0,0,16,14,30
...,...,...,...,...,...,...,...,...,...,...,...,...
2327255,2025-12-31,West Bengal,West Midnapore,721426,0,1,0,0,0,0,0,1
2327256,2025-12-31,West Bengal,West Midnapore,721504,1,0,0,0,0,0,0,1
2327257,2025-12-31,West Bengal,West Midnapore,721506,1,1,0,0,0,0,0,2
2327258,2025-12-31,West Bengal,West Midnapore,721507,1,0,0,0,0,0,0,1
2327259,2025-12-31,West Bengal,West Midnapore,721517,2,1,0,0,0,0,0,3

In [30]:
aadhar_df.shape

(2327260, 12)

In [31]:
aadhar_df.isna().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
total_activity    0
dtype: int64

In [32]:
aadhar_df.duplicated(subset=keys).sum()

np.int64(0)